package com.asm.polybee.view;

import com.asm.polybee.model.SanPham;
import com.asm.polybee.model.TheLoai;
import com.asm.polybee.model.ThuongHieu;
import com.asm.polybee.service.Impl.SanPhamServiceImpl;
import com.asm.polybee.service.Impl.TheLoaiServiceImpl;
import com.asm.polybee.service.Impl.ThuongHieuServiceImpl;
import com.asm.polybee.service.SanPhamService;
import com.asm.polybee.service.TheLoaiService;
import com.asm.polybee.service.ThuongHieuService;
import java.awt.Window;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class ThemSanPhamView extends javax.swing.JFrame {

    private TheLoaiService theLoaiService = new TheLoaiServiceImpl();
    private ThuongHieuService thuongHieuService = new ThuongHieuServiceImpl();
    private SanPhamService sanPhamService = new SanPhamServiceImpl();
    List<TheLoai> listTheLoais = theLoaiService.getAll();
    List<ThuongHieu> listThuongHieus = thuongHieuService.getAll();

    
    
    public ThemSanPhamView() {
        initComponents();

        // Thêm tên thể loại vào model
        DefaultComboBoxModel<String> modelTheLoai = new DefaultComboBoxModel<>();
        for (TheLoai theLoai : listTheLoais) {
            modelTheLoai.addElement(theLoai.getTenTheLoai());
        }
        cbb_theLoai.setModel(modelTheLoai);

        // Thêm tên thương hiệu vào model
        DefaultComboBoxModel<String> modelThuongHieu = new DefaultComboBoxModel<>();
        for (ThuongHieu thuongHieu : listThuongHieus) {
            modelThuongHieu.addElement(thuongHieu.getTenThuongHieu());
        }
        cbb_thuongHieu.setModel(modelThuongHieu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbb_theLoai = new javax.swing.JComboBox<>();
        cbb_thuongHieu = new javax.swing.JComboBox<>();
        txt_maSanPham = new javax.swing.JTextField();
        txt_tenSanPham = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên Sản Phẩm");

        jLabel2.setText("Mã Sản Phẩm");

        jLabel3.setText("Thể Loại");

        jLabel4.setText("Thương Hiệu");

        cbb_theLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbb_thuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbb_theLoai, 0, 132, Short.MAX_VALUE)
                    .addComponent(cbb_thuongHieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_maSanPham)
                    .addComponent(txt_tenSanPham))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_them)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_maSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_tenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btn_them)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbb_theLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbb_thuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        String maSanPham = txt_maSanPham.getText();
        String tenSanPham = txt_tenSanPham.getText();
        String tenTheLoaiDuocChon = (String) cbb_theLoai.getSelectedItem();
        String tenThuongHieuDuocChon = (String) cbb_thuongHieu.getSelectedItem();

        // Sử dụng Java Streams để tìm đối tượng TheLoai tương ứng với tên được chọn
        Optional<TheLoai> optionalTheLoai = listTheLoais.stream()
                .filter(tl -> tl.getTenTheLoai().equals(tenTheLoaiDuocChon))
                .findFirst();

        Optional<ThuongHieu> optionalThuongHieu = listThuongHieus.stream()
                .filter(th -> th.getTenThuongHieu().equals(tenThuongHieuDuocChon))
                .findFirst();

        String idThuongHieuDuocChon = optionalThuongHieu.map(ThuongHieu::getIdThuongHieu).orElse(null);
        String idTheLoaiDuocChon = optionalTheLoai.map(TheLoai::getIdTheloai).orElse(null);

        SanPham sanPham = new SanPham();
        sanPham.setMaSanPham(maSanPham);
        sanPham.setTenSanPham(tenSanPham);
        sanPham.setIdTheLoai(idTheLoaiDuocChon);
        sanPham.setIdThuongHieu(idThuongHieuDuocChon);

        boolean isThemThanhCong = sanPhamService.themSanPham(sanPham);

        if (isThemThanhCong) {
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            txt_maSanPham.setText("");
            txt_tenSanPham.setText("");
            cbb_theLoai.setSelectedIndex(0);
            cbb_thuongHieu.setSelectedIndex(0);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_themActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSanPhamView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_them;
    private javax.swing.JComboBox<String> cbb_theLoai;
    private javax.swing.JComboBox<String> cbb_thuongHieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_maSanPham;
    private javax.swing.JTextField txt_tenSanPham;
    // End of variables declaration//GEN-END:variables
}
